export { default as AppNavigation } from "./ranking/AppNavigation.vue"
export { default as RankingView } from "./ranking/RankingView.vue"
export { default as SearchSchool } from "./search/SearchSchool.vue"
export { default as LoginView } from "./login/LoginView.vue"
// export { default as SelectSchool } from "./search/SelectSchool.vue"